import numpy as np


def propagateStressWaveSLDE((p0,v,rho,dz),measure,Nt):
    """Propagate initial stress profile through inhomogeneous 1D medium 

    Implements staggered leapfrog difference scheme [1] for the acoustic
    propagation of stress waves in 1D piecwise homogeneous elastic medium. 
    The implemented approach is consistent with rigorous theory on optoacoustic
    generation via thermal expansion discussed by Refs. [2] (see Eqs. (1)-(3)),
    [3] (see Eqs. (24)-(25)), [4] (see Eqs. (1)-(3)), and, [5] (see 
    Eqs. (1)-(2)).
    
    Args:
        p0 (numpy array, ndim=1): initial stress profile on equispaced 1D grid
        v (numpy array, ndim=1): local wave speed on equispaced 1D grid
        rho (numpy array, ndim=1): local density on equispaced 1D grid
        dz (float): homogeneous mesh-width of 1D grid
        measure (function): function that implements measurement at each  
            discrete timestep
        Nt (int): amount of timesteps for which propagation is performed  

    Returns:
        p (numpy array, ndim=1): acoustic stress profile at terminal timestep

    Notes:
        callback function takes 4 arguments in the form
        measure(n, dt, u, p), where
            n (int): current time step
            dt (float): increment between consequtive times steps
            u (numpy array, ndim=1): velocity profile
            p (numpy array, ndim=1): acoustic stress profile

    Refs:
        [1] Numerical Recipes in Fortran 77
            Press, WH and Teukolsky, SA and Vetterling, WT and Flannery, BP
            Cambridge University Press (2nd Edition, 2002)

        [2] Laser-generated stress waves in liquids
            Sigrist, M. W. and Kneubuehl, F. K.
            J. Acoust. Soc. Am., 64 (1978) 1652

        [3] Application of photoacoustic sensing techniques
            Tam, AC
            Rev. Mod. Phys., 58 (1986) 381

        [4] Singnal analysis of transients in pulsed photoacoustic spectroscopy
            Schurig, DA and Klunder, GL and Shannon, MA and Russo, RE
            Rev. Sci. Instrum., 64 (1993) 363

        [5] Spherical Model of an Acoustical Wave Generated by Rapid Laser 
            Heating in a Liquid
            Hu, C.-L.
            J. Acoust. Soc. Am., 46 (1969) 728

    """
    # determine timestep that ensures numerical stability
    dt = 0.3*dz/max(v)
    # set scaling coefficient for propagation terms
    C = dt/dz
    # material velocity at two timeslices t[n-1/2] and t[n+1/2] 
    u1 = np.zeros(p0.size-1)
    u = np.zeros(p0.size-1)
    # acoustic stress at two timeslices t[n] and t[n+1] 
    p1 = np.copy(p0)
    p = np.zeros(p0.size)
    # set variable PDE coefficient
    #c1 = 2./(rho[:-1]+rho[1:])  # arithmetic mean 
    c1 = (1./rho[:-1] + 1./rho[1:])/2 # harmonic mean
    c2 = rho*v*v

    # initial conditions already set; only measurement at n=0
    measure(0, dt, u, p)

    # propagate stress and perform measurement for n=1...Nt
    for n in range(1,Nt): 
        
        # advance material velocity
        u[:] = u1[:] - c1[:]*C*(p1[1:] - p1[:-1])
        # advance stress
        p[1:-1] = p1[1:-1] - c2[1:-1]*C*(u[1:] - u[:-1]) 
        # enforce homogeneous Dirichlet BC on stress profiled
        p[0] = 0.; p[-1]=0.
        
        # measurement at timestep n
        measure(n, dt, u, p)

        # advance timestep
        u1[:], p1[:] = u[:], p[:] 

    return p1


# EOF: stressWavePropagation1DSLDE.py
